---
name: Docker Image CI
'on':
  push:
    branches:
      - main
    tags:
      - 'v*.*.*.'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: |
            visualsolana/workspace
          tags: |
            type=semver,pattern={{major}}.{{minor}}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true          
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}